### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by javier-smith** [JannikLassahn/unity-videoplayer-helper#1]
Hello I've just started to try your code it looks promising! however i've checked that it doesn't work for android, right? or am I doing something wrong? Thanks!

**Comment by JannikLassahn** [comment]
I haven't tested with android yet, but I'll take a look. Feel free to make a PR if you come across a bug.

**Comment by talyh** [comment]
I saw it crashing on Android too.
So I disabled all this and added the standard Unity VideoPlayer. Still crashed.
I then tried an empty project, just with the VideoPlayer. Also crashed.
So I believe this plugin is not at fault.

Issue https://forum.unity.com/threads/videoplayer-crash-on-android-workarounds.697109/ at Unity Forums to try and get to the bottom of this.
