### ISSUE TITLE
Is WebGL local video not supported?

### ISSUE THREAD

**Issue by OscarUnity** [JannikLassahn/unity-videoplayer-helper#2]

**Comment by JannikLassahn** [comment]
You can prefix the path to a local file with _file://_, e.g. _file://C:\myvideo.mp4_.

**Comment by seoyeo** [comment]
Hi，When I try to play a local file and report  errors : "WindowsVideoMedia error 0x8007007b while reading file://C:\myvideo.mp4", "VideoPlayer cannot play url : file://C:\myvideo.mp4" "[Video Controller] VideoPlayer cannot play url : file://C:\myvideo.mp4" ,What should I do? thank you!

**Comment by JannikLassahn** [comment]
This error can happen in one of these cases
* you use an older version of Unity that sometimes fails to load the file (I just tested with 2018.4.4 and it works)
* the path to your video is not correct
* the video codec is not supported (see [docs](https://docs.unity3d.com/ScriptReference/Video.VideoPlayer.html))

Hope you figure it out!

I also tested the YouTube sample with WebGL and it seems like one really can't load a local video file. Could have sworn it worked last time I tried...

**Comment by seoyeo** [comment]
Thank you for your reply. Maybe there's something wrong with my Unity version
