### ISSUE TITLE
Video Caching Progress

### ISSUE THREAD

**Issue by TraditoreZ** [JannikLassahn/unity-videoplayer-helper#3]
How to display the video cache progress?

**Comment by JannikLassahn** [comment]
The VideoPlayer API does not provide ways to get a value for caching progress, therefore you can only show an indeterminate progress indicator. The [VideoPresenter](https://github.com/JannikLassahn/unity-videoplayer-helper/blob/master/Docs/Scripts.md#videopresentercs) script has the corresponding field *Loading Indicator*.
