### ISSUE TITLE
Right click & choose Video -> Video Player with Controls, nothing is created

### ISSUE THREAD

**Issue by cdr9042** [JannikLassahn/unity-videoplayer-helper#4]
I followed the instruction: To add a template for the video player click right in the Hierarchy panel and choose Video -> Video Player with Controls
But when I do this, no new object is created, nothing happens at all. No errors, no warning

**Comment by JannikLassahn** [comment]
Seems like the prefab that contains the template somehow wasn't included in the .unitypackage.
I just made a [new release](https://github.com/JannikLassahn/unity-videoplayer-helper/releases/tag/v0.1.1). Hope it works now.

**Comment by cdr9042** [comment]
That was fast! Thanks
