### ISSUE TITLE
play youtube video

### ISSUE THREAD

**Issue by GowthamAlric** [JannikLassahn/unity-videoplayer-helper#7]
how to play the youtube video url in the Unity, when i tried its not working.
else kindly give me the idea that how to play the custom video.

**Comment by JannikLassahn** [comment]
The package only provides the UI.
Take a look at the [Unity documention](https://docs.unity3d.com/2020.2/Documentation/Manual/VideoSources-FileCompatibility.html) for supported formats.  Also, there are other projects on GitHub like [UnityYouTubePlayer](https://github.com/iBicha/UnityYoutubePlayer) that you can use.
