### ISSUE TITLE
Changing Video?

### ISSUE THREAD

**Issue by WarlyFarly-Github** [JannikLassahn/unity-videoplayer-helper#9]
I'm using this asset for a project and am wondering how to change the video.

**Comment by JannikLassahn** [comment]
I believe it should be possible by calling `PrepareForUrl(string url)` in [VideoController](https://github.com/JannikLassahn/unity-videoplayer-helper/blob/master/Docs/Scripts.md#methods). If `startAfterPreparation` is enabled, the video should automatically start.
